################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q7.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q31.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f16.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f32.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f64.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q15.c \
../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q31.c 

SREC += \
ArmSync_Solution_CPU0.srec 

C_DEPS += \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q7.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q31.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f16.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f32.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f64.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q15.d \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q31.d 

OBJS += \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_accumulate_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_max_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_min_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_power_q7.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_std_q31.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f16.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f32.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_f64.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q15.o \
./ra/arm/CMSIS-DSP/Source/StatisticsFunctions/arm_var_q31.o 

MAP += \
ArmSync_Solution_CPU0.map 


# Each subdirectory must supply rules for building sources it contributes
ra/arm/CMSIS-DSP/Source/StatisticsFunctions/%.o: ../ra/arm/CMSIS-DSP/Source/StatisticsFunctions/%.c
	$(file > $@.in,-mthumb -mfloat-abi=hard -mcpu=cortex-m85+nopacbti -O1 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-strict-aliasing -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -g -D_RENESAS_RA_ -D_RA_CORE=CPU0 -D_RA_ORDINAL=1 -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra_cfg/fsp_cfg/bsp" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/npu_model" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/tasks/MotionPlanningTask" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/ik/include/public" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/ik/include/private" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/utils" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/arm" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/flash" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/tasks/IKTask" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/tasks/NPUTask" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/tasks/UITask" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/tasks/CPUCommTask" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/tasks/UartRecvTask" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/tasks/NormalizeTask" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/tasks/FusionTask" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/app/tasks" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/FreeRTOS/FreeRTOS-Cpp/include" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/FreeRTOS/FreeRTOS-Kernel/portable/RM_FSP_PORT" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src/FreeRTOS/FreeRTOS-Kernel/include" -I"." -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra_gen" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra_cfg/fsp_cfg" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/arm/CMSIS_6/CMSIS/Core/Include" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/src" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/fsp/inc" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/fsp/inc/api" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/fsp/inc/instances" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/npu/ethos-u-core-driver/include" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/arm/CMSIS-NN/Include" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/arm/CMSIS-NN" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/npu/ethos-u-core-software/lib/layer_by_layer_profiler/include" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/npu/ethos-u-core-software/lib/ethosu_monitor/include" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/npu/ethos-u-core-software/lib/ethosu_profiler/include" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/npu/ethos-u-core-software/lib/crc/include" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/npu/ethos-u-core-software/lib/arm_profiler/include" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/arm/CMSIS-View/EventRecorder/Include" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/arm/CMSIS-View/EventRecorder/Config" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/npu/tflite-micro" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/npu/ruy" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/npu/gemmlowp" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/fsp/src/rm_ethosu" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/arm/CMSIS-DSP/PrivateInclude" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/arm/CMSIS-DSP/Include" -I"E:/Folders/Documents/Dev/Renesas/RA8P1/Projects/ArmSync_Solution_CPU0/ra/npu/flatbuffers/include" -std=c11 -Wno-stringop-overflow -Wno-format-truncation -w -flax-vector-conversions --param=min-pagesize=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" -x c "$<")
	@echo Building file: $< && arm-none-eabi-gcc @"$@.in"

